CREATE TABLE barang (
	id	INTEGER NOT NULL,
	nama	TEXT NOT NULL,
	stok	INTEGER DEFAULT 0,
	harga	INTEGER DEFAULT 0,
	PRIMARY KEY(id)
);

CREATE TABLE users (
	id	INTEGER,
	username	TEXT NOT NULL UNIQUE,
	password	TEXT NOT NULL,
	added	INTEGER NOT NULL,
	access TEXT NOT NULL DEFAULT 'users',
	money	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(id AUTOINCREMENT)
);