DROP TABLE IF EXISTS barang;
CREATE TABLE barang (
	id	INTEGER NOT NULL,
	nama	TEXT NOT NULL,
	stok	INTEGER DEFAULT 0,
	harga	INTEGER DEFAULT 0,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	username	TEXT NOT NULL UNIQUE,
	password	TEXT NOT NULL UNIQUE,
	added	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(username)
);